#!/bin/bash
set -ex

curl -v -o src/main/resources/openapi.yaml https://api.entropy-data.com/openapi.yaml
schemas=("odcs-json-schema-v3.1.0.json" "dataproduct-0.0.1.json" "odps-json-schema-v1.0.0.json")
mkdir -p src/main/resources/schemas
for schema in "${schemas[@]}"; do
  curl -v -o src/main/resources/schemas/"$schema" https://api.entropy-data.com/schemas/"$schema"
done
